on: 
    workflow_dispatch:

name: Atlas CLI List Clusters Example

env:
  MONGODB_ATLAS_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  MONGODB_ATLAS_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.ORG_ID }} # default organisation ID
  MONGODB_ATLAS_PROJECT_ID: ${{ secrets.PROJECT_ID }} # default project ID

jobs:
  list-clusters:
    runs-on: ubuntu-latest

    steps:
      - name: Setup AtlasCLI
        uses: mongodb/atlas-github-action@v0.2.0
      - name: List Clusters
        shell: bash
        run: |
          atlas cluster list --projectId "$MONGODB_ATLAS_PROJECT_ID" --output json > clusters.json
      - name: Upload Cluster List
        uses: actions/upload-artifact@v4
        with:
          name: clusters-list
          path: clusters.json
