name: Tests
on:
  workflow_dispatch:

env:
  MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
  MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGODB_ATLAS_PROJECT_ID }}
  MONGODB_ATLAS_OPS_MANAGER_URL: "https://cloud-dev.mongodb.com/"
  MONGODB_ATLAS_SILENCE_STORAGE_WARNING: "true"

jobs:
  test-service-account-authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run generate-service-account.sh
        id: generate_sa
        env:
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
        run: |
          bash .github/generate-service-account.sh
      - name: Actual test
        env: 
            MONGODB_ATLAS_PUBLIC_API_KEY: ""
            MONGODB_ATLAS_PRIVATE_API_KEY: ""
            MONGODB_ATLAS_CLIENT_ID: ${{ steps.generate_sa.outputs.client-id }}
            MONGODB_ATLAS_CLIENT_SECRET: ${{ steps.generate_sa.outputs.client-secret }}
        uses: mongodb/atlas-github-action@v0.2.1
        id: create-project
        with:
          create-project-name: ${{ github.run_id }}-project1
      - name: delete project
        env: 
            MONGODB_ATLAS_PUBLIC_API_KEY: ""
            MONGODB_ATLAS_PRIVATE_API_KEY: ""
            MONGODB_ATLAS_CLIENT_ID: ${{ steps.generate_sa.outputs.client-id }}
            MONGODB_ATLAS_CLIENT_SECRET: ${{ steps.generate_sa.outputs.client-secret }}
        uses: mongodb/atlas-github-action@v0.2.1
        with:
          delete-project-id: ${{ steps.create-project.outputs.create-project-id }}

      - name: Run terminate-service-account.sh
        env:
          MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_API_KEY }}
          MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_API_KEY }}
          MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
          CLIENT_ID: ${{ steps.generate_sa.outputs.client-id }}
        run: |
          bash .github/terminate-service-account.sh
